source "https://rubygems.org" do

    gem "mysql2", ">= 0.4.4"
    gem "rom", ">= 2.0.1"
    gem "rack", ">= 2.0.1"
    # gem "rake", ">= 11.3.0"
    gem "grape", ">= 0.18.0"
    gem "json", ">= 2.0.2"

end